[package]
name = "imap"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
oxc = { version = "0.72.0", features = ["ast_visit"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
walkdir = "2.5.0"
yansi = "1.0.1"
